Mosl 28
ChrisOfNormandy/senior-design pull request #23
Opened 2021-03-23 15:42 UTC by ImportedGlue891

I haven't pushed anything since yesterday, but I wanted to make sure I made the pr before i accidentally forget again.

2021-04-12 18:12 UTC, Slayer799 commented on ESB/services/aws/athena.js
> +                    fs.appendFileSync('../athena_report.JSON','{"Athena_report":['+JSON.stringify(json.data)+"]},\n");
Nit pick, massive tab here bring it back in line please

2021-04-12 18:25 UTC, Slayer799 commented on ESB/services/aws/athena.js
> +        if(req.body.data == '' || typeof req.body != 'object' || req.body.type != 'application/json')
req.body.data could be empty and we should still take it.

2021-04-12 18:39 UTC, Slayer799 commented on ESB/services/aws/athena.js
> +        if(req.body.data == '' || typeof req.body.data != "string" || typeof req.body != 'object' && (req.body.type != 'text/csv' || req.body.type != 'application/csv'))
It does not actually allow multiple files to be added.

2021-04-13 04:19 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +        if(req.body.data == '' || typeof req.body.data != "string" || typeof req.body != 'object' && (req.body.type != 'text/csv' || req.body.type != 'application/csv'))
This comment was in regards to the post_csv being able to have multiple csv files chained to it and work as intended. It was not about the if condition.

2021-04-13 04:19 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +        if(req.body.data == '' || typeof req.body != 'object' || req.body.type != 'application/json')
Fixed

2021-04-13 04:20 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +                    fs.appendFileSync('../athena_report.JSON','{"Athena_report":['+JSON.stringify(json.data)+"]},\n");
Fixed

2021-04-13 18:00 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +        if(typeof req.body != 'object' || req.body.type != 'application/json')
You're not checking to see if req.body.type exists (undefined will not equal a string, but the input may be valid), or the format of the input is what's expected.

2021-04-13 18:00 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +        else if(req.query.key === undefined)
req.query.key is never referenced past this condition.

2021-04-13 18:00 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +            if(fs.readFileSync('../athena_report.JSON').includes('[') == false)
You should not be reading a local file.

2021-04-13 18:01 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +                fs.appendFileSync('../athena_report.JSON',"[");
Nor should you be appending to a local file.

2021-04-13 18:01 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +            res.download('../athena_report.JSON',json.name);
This can be simplified to setting the response header 'content-type' to 'application/json' and sending the object as the response.

2021-04-13 18:06 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +        if(typeof req.body.data != "string" || typeof req.body != 'object' && (req.body.type != 'text/csv' || req.body.type != 'application/csv'))
This is a jumbled mess of conditions that doesn't make a lot of sense together.
For one, it appears you're not checking the file type the editor provides CSV files when added, meaning they'll never be accepted.
Two, the structure of this condition chain is kind of wacky. X || Y && (A || B) ? Surely this can be simplified a bit, especially for readability.
Three, if it is a CSV, you're never converting it to a usable format. An example string is "a,b,c,d,e\nf,g,h,i,j"
That's 2 rows of 5 columns that can be easily converted to an array of arrays, which this stub should be doing to mimic an analysis.

2021-04-13 18:33 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +        else if(req.query.key === undefined)
Do you want me to remove this since I never reference it again?

2021-04-13 18:39 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +            if(fs.readFileSync('../athena_report.JSON').includes('[') == false)
Should I remove every instance when I made this reference that local file?

2021-04-13 19:20 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +            res.download('../athena_report.JSON',json.name);
So something like
Var myhead=new headers();
Myhead.set("content-type","application/json");
Myhead.appnd("data",json.data);
?

2021-04-13 19:43 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> +        if(typeof req.body != 'object' || req.body.type != 'application/json')
So (req.body.type === undefined)?

2021-04-13 23:17 UTC, ImportedGlue891 commented on ESB/services/aws/athena.js
> -            data: {}
I'll fix this. I didn't realize I changed this.

2021-04-14 02:18 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +const fs =require('fs');
You should not be using fs.

2021-04-14 02:19 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +        if(typeof req.body != 'object' && req.body.type == "application/json")
If req.body contains a property, it's by default an object.

2021-04-14 02:22 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +            res.json(json);
You're just returning the original data. That's not the use case of this stub.

2021-04-14 02:23 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +        if(req.body===undefined || req.body.type != "application/vnd.ms-excel")
req.body is never undefined. You're also only checking for one valid file type, assuming that the property "type" exists in req.body.

2021-04-14 02:23 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +            const results = Array(csv.data).reduce((acc,x)=>{
You clearly copy/pasted this.
Don't.

2021-04-15 16:29 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +            json.push({
Files are not formatted like this.
Only _attachments_ that are files are, and the reason for that is they're not responses, just objects.
So from something like this, it should just be objects.

And since you're using content type incorrectly here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

And you're still assuming req.body.data is defined.

2021-04-15 16:30 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +        else{//for stubs
This whole thing is a stub? What do you mean "for stubs?"

2021-04-15 16:33 UTC, ChrisOfNormandy commented on ESB/services/aws/athena.js
> +            if(Array.isArray(req.body)){
Not entirely sure what you're trying to do here, because for one you're never checking the individual contents of the array if it is an array of items.

Two, toString is undefined.

Three, you have a console log, and you're doing the iteration of the for loop incorrectly. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

Four, you're sending off the content using different formats for both conditions. You should have a standard output regardless of the input (given it's valid) and a standard error output (like a string, which you're doing here).

2021-04-15 16:38 UTC, ChrisOfNormandy requested changes
>

2021-04-24 21:38 UTC, closed without merging